### PR TITLE
Dynamic Path for LogoHeader + copy icon image

### PR DESCRIPTION
**Pull request by gogodanny**
1. The copy icon is broken (if you didn't with theme name "pear" or when it's not installed in first level).
   Therefore, i made the image path dynamically according to the theme path.
2. Header logo and text link is not dynamic (will not work wordpress install in sub folder using custom domain name), therefore i use wp standard variable to replace it.

### CODE REVIEW

**Comment by itreptil** [comment]
@simplebits we really need this change. please merge this two commits

**Comment by simplebits** [comment]
Done!

**Comment by itreptil** [comment]
thanks !

**Comment by gudnm** [comment]
I made a pull request (#28) to wrap up this issue. The footer logo was left out.

**Pull request merged**
